[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crypto>=1.4.1",
    "gmpy2>=2.2.1",
    "numpy>=2.3.4",
    "pycryptodome>=3.23.0",
    "sympy>=1.14.0",
]
